package openidUtils

var TestOpenidProviderMetadataApp1 = map[string]interface{}{
	"issuer":                                "https://server.example.com",
	"authorization_endpoint":                "https://server.example.com/connect/authorize",
	"token_endpoint":                        "https://server.example.com/connect/token",
	"token_endpoint_auth_methods_supported": []string{"client_secret_basic", "private_key_jwt"},
	"token_endpoint_auth_signing_alg_values_supported": []string{"RS256", "ES256"},
	"userinfo_endpoint":                           "https://server.example.com/connect/userinfo",
	"check_session_iframe":                        "https://server.example.com/connect/check_session",
	"end_session_endpoint":                        "https://server.example.com/connect/end_session",
	"jwks_uri":                                    "https://server.example.com/jwks.json",
	"registration_endpoint":                       "https://server.example.com/connect/register",
	"scopes_supported":                            []string{"openid", "profile", "email", "address", "phone", "offline_access"},
	"response_types_supported":                    []string{"code", "code id_token", "id_token", "token id_token"},
	"acr_values_supported":                        []string{"urn:mace:incommon:iap:silver", "urn:mace:incommon:iap:bronze"},
	"subject_types_supported":                     []string{"public", "pairwise"},
	"userinfo_signing_alg_values_supported":       []string{"RS256", "ES256", "HS256"},
	"userinfo_encryption_alg_values_supported":    []string{"RSA1_5", "A128KW"},
	"userinfo_encryption_enc_values_supported":    []string{"A128CBC-HS256", "A128GCM"},
	"id_token_signing_alg_values_supported":       []string{"RS256", "ES256", "HS256"},
	"id_token_encryption_alg_values_supported":    []string{"RSA1_5", "A128KW"},
	"id_token_encryption_enc_values_supported":    []string{"A128CBC-HS256", "A128GCM"},
	"request_object_signing_alg_values_supported": []string{"none", "RS256", "ES256"},
	"display_values_supported":                    []string{"page", "popup"},
	"claim_types_supported":                       []string{"normal", "distributed"},
	"claims_supported":                            []string{"sub", "iss", "auth_time", "acr", "name", "given_name", "family_name", "nickname", "profile", "picture", "website", "email", "email_verified", "locale", "zoneinfo", "http://example.info/claims/groups"},
	"claims_parameter_supported":                  true,
	"service_documentation":                       "http://server.example.com/connect/service_documentation.html",
	"ui_locales_supported":                        []string{"en-US", "en-GB", "en-CA", "fr-FR", "fr-CA"},
}

var TestOpenidProviderMetadataApp2 = map[string]interface{}{
	"issuer":                                "https://server.example.com",
	"authorization_endpoint":                "https://server.example.com/connect/authorize",
	"token_endpoint":                        "https://server.example.com/connect/token",
	"token_endpoint_auth_methods_supported": []string{"client_secret_basic", "private_key_jwt"},
	"token_endpoint_auth_signing_alg_values_supported": []string{"RS256", "ES256"},
	"userinfo_endpoint":                           "https://server.example.com/connect/userinfo",
	"check_session_iframe":                        "https://server.example.com/connect/check_session",
	"end_session_endpoint":                        "https://server.example.com/connect/end_session",
	"jwks_uri":                                    "https://server.example.com/jwks.json",
	"registration_endpoint":                       "https://server.example.com/connect/register",
	"scopes_supported":                            []string{"openid", "profile", "email", "address", "phone", "offline_access"},
	"response_types_supported":                    []string{"code", "code id_token", "id_token", "token id_token"},
	"acr_values_supported":                        []string{"urn:mace:incommon:iap:silver", "urn:mace:incommon:iap:bronze"},
	"subject_types_supported":                     []string{"public", "pairwise"},
	"userinfo_signing_alg_values_supported":       []string{"RS256", "ES256", "HS256"},
	"userinfo_encryption_alg_values_supported":    []string{"RSA1_5", "A128KW"},
	"userinfo_encryption_enc_values_supported":    []string{"A128CBC-HS256", "A128GCM"},
	"id_token_signing_alg_values_supported":       []string{"RS256", "ES256", "HS256"},
	"id_token_encryption_alg_values_supported":    []string{"RSA1_5", "A128KW"},
	"id_token_encryption_enc_values_supported":    []string{"A128CBC-HS256", "A128GCM"},
	"request_object_signing_alg_values_supported": []string{"none", "RS256", "ES256"},
	"display_values_supported":                    []string{"page", "popup"},
	"claim_types_supported":                       []string{"normal", "distributed"},
	"claims_supported":                            []string{"sub", "iss", "auth_time", "acr", "name", "given_name", "family_name", "nickname", "profile", "picture", "website", "email", "email_verified", "locale", "zoneinfo", "http://example.info/claims/groups"},
	"claims_parameter_supported":                  true,
	"service_documentation":                       "http://server.example.com/connect/service_documentation.html",
	"ui_locales_supported":                        []string{"en-US", "en-GB", "en-CA", "fr-FR", "fr-CA"},
}
